# Generated by Django 2.1.5 on 2019-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190407_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/data'),
        ),
    ]
